spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/home?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  devtools:     #热部署
    restart:
      enabled: true
mybatis-plus:
  type-aliases-package: com.hz.pojo